### ISSUE TITLE
Speed-based poise Spirit Vector (aka "longboard")

### ISSUE THREAD

**Issue by sleepingdragoninn** [HamaIndustries/spirit-vector#23]
A completely different _base_ spirit vector that doesn't gain poise from tricks. Poise constantly decays below a minimum speed (at all times), and regenerates when sliding above a key speed. Poise doesn't regenerate in the air, so you can still only chain air runes so long.

**Comment by HamaIndustries** [comment]
dream vector implemented 06e8fe19d664e4ed89337d57757f5c5b27abcce2
